name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
        shell: cmd

      - name: Compile
        run: haxelib run lime build windows

      - name: Publish artifact
        uses: actions/upload-artifact@main
        with:
          name: Flixel-Project
          path: "export/release/windows/bin"
