name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Restore existing build cache
        uses: actions/cache@main
        with:
          key: cache-build-windows
          path: |
            .haxelib/
            export/windows/bin
            export/windows/obj
          restore-keys: |
            cache-build-windows

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install hxcpp --quiet
        shell: cmd

      - name: Compile
        run: haxelib run lime build windows

      - name: Publish artifact
        uses: actions/upload-artifact@main
        with:
          name: Flixel-Project
          path: "export/windows/bin"

      - name: Clear already existing cache
        uses: actions/github-script@main
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-windows") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }

      - name: Uploading new cache
        uses: actions/cache@main
        with:
          key: cache-build-windows
          path: |
            .haxelib/
            export/windows/bin
            export/windows/obj
          restore-keys: |
            cache-build-windows
